Change build_and_push_docker_image.yml to only push image to GHCR when acceptance test successful.

diff --git a/.github/workflows/build_and_push_docker_image.yml b/.github/workflows/build_and_push_docker_image.yml
--- a/.github/workflows/build_and_push_docker_image.yml
+++ b/.github/workflows/build_and_push_docker_image.yml
@@ -12,7 +12,7 @@ env:
 jobs:
   # Job builds docker image and pushes it to GHCR
   build-and-push:
-    name: Build and push docker image to Github registry
+    name: Builddocker image
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -44,11 +44,10 @@ jobs:
             type=semver,pattern={{major}}
             type=sha
 
-      - name: Build and push Docker images
+      - name: Build Docker image
         run: |
           # Build and push each service defined in docker-compose.yml
           docker compose -f ${{ env.COMPOSE_FILE }} build
-          docker compose -f ${{ env.COMPOSE_FILE }} push
 
   # Job runs acceptance tests
   acceptance-test:
@@ -66,12 +65,9 @@ jobs:
         run: |
           docker network create VoltCast_Network
           
-          docker run -d --name api-gateway -p 22200:22200 \
-            -e "DB_NAME=$DB_NAME" \
-            -e "ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES" \
-            -e "JWT_SECRET=$JWT_SECRET" \
-            -e "ALGORITHM=$ALGORITHM" \
-            ghcr.io/voltcast-a-ase-project/api-gateway-python/api-gateway:latest
+          docker compose -f ${{ env.COMPOSE_FILE }} down -v || true
+          
+          DB_NAME=$DB_NAME,ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES,JWT_SECRET=$JWT_SECRET,ALGORITHM=$ALGORITHM docker compose -f ${{ env.COMPOSE_FILE }} up -d -p 22200:22200 --build --force-recreate api-gateway
 
           docker run -d --name fronius-ms -p 8081:8081 \
             -e MOCKING_ENABLED=true \
@@ -96,6 +92,17 @@ jobs:
           
           docker network connect VoltCast_Network alerting-ms
           
+      - name: Wait for API-Gateway
+        run: |
+          for i in {1..15}; do
+            if curl -s http://localhost:22200/api/v1/login; then
+              echo " API-Gateway is up!"
+              break
+            else
+              echo " Waiting for API-Gateway..."
+              sleep 2
+            fi
+          done
 
       - name: Install Python, Java Runtime and Taurus
         run: |
@@ -108,5 +115,53 @@ jobs:
 
       - name: Run Acceptance Tests
         run: |
-          source .venv/bin/activate
-          bzt acceptance_tests.jmx
+          source venv/bin/activate
+          ART_DIR="$PWD/artifacts_acceptance"
+          echo "Artifacts dir: $ART_DIR"
+          mkdir -p "$ART_DIR"
+          bzt acceptance_tests.jmx -o settings.artifacts-dir="$ART_DIR" -o modules.console.disable=true -l "$ART_DIR/bzt.log" || true,
+
+      - name: Check JMeter/Taurus results
+        run: |
+          ERROR_RATE=$(awk -F',' '
+          NR==1 { next }
+          {
+            total++
+            if ($8 == "false") errors++
+          }
+          END {
+            if (total > 0)
+              printf "%.2f\n", (errors / total) * 100
+            else
+              print "0.00"
+          }
+          ' artifacts_acceptance/kpi.jtl)
+          THRESHOLD=10
+          echo "Error rate: $ERROR_RATE %"
+          if (( $(echo "$ERROR_RATE > THRESHOLD" | bc -l) )); then
+            echo "Error rate too high, failing the job!"
+            exit 1
+          fi
+          
+          - name: Stop test containers
+            if: always()
+            run: docker compose -f ${{ env.COMPOSE_FILE }} down -v
+          
+
+  push-docker-image:
+    name: Push API-Gateway to GHCR
+    runs-on: ubuntu-latest
+    needs: [ acceptance-test ]
+    steps:
+      - uses: actions/checkout@v4
+      - name: Log in to GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build and push production image
+        run: |
+          docker compose -f ${{ env.COMPOSE_FILE }} build --no-cache api-gateway
+          docker compose -f ${{ env.COMPOSE_FILE }} push api-gateway
